Spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labreserve?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: '123456'
  http:
    encoding:
    force: true
    charset: UTF-8
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
    web:
      resources:
        static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  data:
    redis:
      port: 6379
      database: 0
      timeout: 5000
      host: 127.0.0.1
      max-wait: 30000    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 20     # 连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      password: 123456 # 密码,默认密码为空
  session:
    store-type: redis #是否将session存到redis  none/redis
    timeout: 1000 # 配置session在redis中的过期时间
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.labreservesystem.bean
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: false
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  helper-dialect: mysql
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
